[project]
name = "boss-bidding-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash==2.17.1",
    "dash-bootstrap-components==1.5.0",
    "pandas==2.2.2",
    "plotly==5.17.0",
]
